# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EeVjLma9vNdK264uyexi2pdKTZLB1U48
"""

a=10
b=20
c=a+b
c

